### PR TITLE
refactored: apply some principles like DRY or separation of concerns

### PR DESCRIPTION
**Pull request by ugort**
The biggest change is the following: 
- moved the code for hiding/showing of labels from MYBlurIntroductionView to class MYIntroductionPanel
- apply [MYBlurIntroductionView introduction: didFinishWithType:] after animation finished
- removed duplicated code in init methods

### CODE REVIEW

**Comment by MatthewYork** [comment]
@ugort I really like the changes you made and am getting ready to merge this. However, when I loaded up the sample application in the repository, it did not build. Is there any way you could fix the elements that have changed (specifically enabling/disabling the introduction view from a custom panel).

Looking forward to the updated example. If everything holds from there, I will merge your changes.

**Comment by fulldecent** [comment]
I am liking the PR, is there any progress on this code review?

**Comment by MatthewYork** [comment]
I have not heard from ugort, however I am planning to do a re-write soon with full landscape and iPad support.

**Comment by fulldecent** [comment]
Very good news, +star!

**Comment by ugort** [comment]
I did commit an update long time ago. But omitted a comment, maybe because of that you did not notice.

**Pull request merged**
